// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQcHnq0qRH_xXXjlepiBAH1G2rE187ulk',
    appId: '1:753842349493:web:934726ba088f7aa22e25fc',
    messagingSenderId: '753842349493',
    projectId: 'islamiclifestyle-dbc70',
    authDomain: 'islamiclifestyle-dbc70.firebaseapp.com',
    storageBucket: 'islamiclifestyle-dbc70.firebasestorage.app',
    measurementId: 'G-JD6WEV84DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI8KQn7_u7SBwDfw2hUwb0MAHRFW_-Op8',
    appId: '1:753842349493:android:d46c91a1c69a1a5f2e25fc',
    messagingSenderId: '753842349493',
    projectId: 'islamiclifestyle-dbc70',
    storageBucket: 'islamiclifestyle-dbc70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs5qD3fuMCP7i9eP5M8_lcL5jY1rQYqz4',
    appId: '1:753842349493:ios:551455389fffcdb52e25fc',
    messagingSenderId: '753842349493',
    projectId: 'islamiclifestyle-dbc70',
    storageBucket: 'islamiclifestyle-dbc70.firebasestorage.app',
    iosClientId: '753842349493-767ovj65atlmq74dotvqj4vfopj5ivmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.islamicLifestyle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs5qD3fuMCP7i9eP5M8_lcL5jY1rQYqz4',
    appId: '1:753842349493:ios:551455389fffcdb52e25fc',
    messagingSenderId: '753842349493',
    projectId: 'islamiclifestyle-dbc70',
    storageBucket: 'islamiclifestyle-dbc70.firebasestorage.app',
    iosClientId: '753842349493-767ovj65atlmq74dotvqj4vfopj5ivmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.islamicLifestyle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQcHnq0qRH_xXXjlepiBAH1G2rE187ulk',
    appId: '1:753842349493:web:18d86fb8440b94ee2e25fc',
    messagingSenderId: '753842349493',
    projectId: 'islamiclifestyle-dbc70',
    authDomain: 'islamiclifestyle-dbc70.firebaseapp.com',
    storageBucket: 'islamiclifestyle-dbc70.firebasestorage.app',
    measurementId: 'G-R87TVZQRXZ',
  );
}
